// scripts/floorNumber.js
(function(){

    'use strict';

    angular
        .module('formlyApp')
        .factory('floorNumber', floorNumber);

    function floorNumber() {
        function getfloorNumber() {
            return [
                {
                    "name": "SS",
                    "value":"floor_SS"
                },
                {
                    "name":"REZ",
                    "value":"floor_REZ"
                },
                {
                    "name":"1",
                    "value":"floor_1"
                },
                {
                    "name":"2",
                    "value":"floor_2"
                },
                {
                    "name":"3",
                    "value":"floor_3"
                },
                {
                    "name":"4",
                    "value":"floor_4"
                },
                {
                    "name":"5",
                    "value":"floor_5"
                },
                {
                    "name":"6",
                    "value":"floor_6"
                },
                {
                    "name":"7",
                    "value":"floor_7"
                },
                {
                    "name":"8",
                    "value":"floor_8"
                },
                {
                    "name":"9",
                    "value":"floor_9"
                },
                {
                    "name":"10",
                    "value":"floor_10"
                },
                {
                    "name":"11",
                    "value":"floor_11"
                },
                {
                    "name":"12",
                    "value":"floor_12"
                },
                {
                    "name":"13",
                    "value":"floor_13"
                },
                {
                    "name":"14",
                    "value":"floor_14"
                },
                {
                    "name":"15",
                    "value":"floor_15"
                },
                {
                    "name":"16",
                    "value":"floor_16"
                },
                {
                    "name":"17",
                    "value":"floor_17"
                },
                {
                    "name":"18",
                    "value":"floor_18"
                },
                {
                    "name":"19",
                    "value":"floor_19"
                },
                {
                    "name":"20",
                    "value":"floor_20"
                },
                {
                    "name":"21",
                    "value":"floor_21"
                },
                {
                    "name":"22",
                    "value":"floor_22"
                },
                {
                    "name":"23",
                    "value":"floor_23"
                },
                {
                    "name":"24",
                    "value":"floor_24"
                },
                {
                    "name":"25",
                    "value":"floor_25"
                },
                {
                    "name":"26",
                    "value":"floor_26"
                },
                {
                    "name":"27",
                    "value":"floor_27"
                },
                {
                    "name":"28",
                    "value":"floor_28"
                },
                {
                    "name":"29",
                    "value":"floor_29"
                },
                {
                    "name":"30",
                    "value":"floor_30"
                },
             ];
        }
        return {
            getfloorNumber: getfloorNumber
        }
    }
})();